### ISSUE TITLE
Data tile BE: Transactions burning most steps by entrypoint ID

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#10]
Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

Create an API endpoint in the https://github.com/walnuthq/starkflare-indexer backend repo that accepts two parameters: contract hash and entrypoint selector. The endpoint should return a list of transactions for the given contract and entrypoint, sorted by the number of steps consumed in descending order.

The returned data for each transaction should include:
- Transaction hash 
- Number of steps consumed
- Timestamp of the transaction

Follow the guidelines outlined in the [starkflare-indexer](https://github.com/walnuthq/starkflare-indexer) repository. Note that this endpoint should be implemented separately from the `get_common_data` endpoint as it requires specific arguments.

**Comment by KeneePatel** [comment]
Hey @mazurroman,

I would like to tackle this issue. Just wanted some references to understand the entrypoints and on which language is the backend going to be implemented in? Can you give some directions, so then I will be able to come up with a strategy to handle the task.

**Comment by aweolumidedavid** [comment]
Hi, I will to take this up

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by danielcdz** [comment]
Hello! I would like to help with this one!
I think this issue can take me about 2 to 5 days to complete, exactly the time limit of the OD Hack!
I have over 3 years of experience as a software engineer and specially working with Golang,developing micro services and backend applications, I want to apply this knowledge in web3 and blockchain projects, on the other hand, this is my 2nd OD Hack,in the last one i contributed to Go projects for Nethermind

**Comment by aweolumidedavid** [comment]
@mazurroman hi, you can call me David.
I am a software engineer experienced in building scalable solutions. I have experience building NodeJs solutions either with expressJs, NestJs or fastify. I have also work with different type of database both NoSQL and Relational Databases like Postgres, MySql and MSSServer using typerOrm.

To implement the API, I will do the following
- I will be working in the indexer/src module which have more that one responsibility as it contains the account interface, the db congiguration for postgres, and the methods/functions to call.
- I will create new folder and a file in the folder for interface and move the account interface there
- create a new folder for the configs and create a file and move the postgres connection function there
- import the interface and the config in the account-call.ts
- Write a function to query the PostgreSQL database for transactions matching the provided contractHash and entrypointSelector, sorting the results by the number of steps consumed in descending order.
I will ensure that the response includes the transaction hash, number of steps consumed, and timestamp.
-create a new folder called controller and create a new route for the API endpoint that will accept contractHash and entrypointSelector as query parameters.
- I will ensure that validation by add the validation middleware method checks the query parameters.
- for the validator, I can use joi package to validate accordingly
- I will make sure the newly created files and routes follow the existing project structure and guidelines outlined in the starkflare-indexer repository.
Thank you very much.

**Comment by mazurroman** [comment]
Assigning to @aweolumidedavid who provided the most detailed information on how to approach this issue

**Comment by mazurroman** [comment]
Apologies for a confusion here. @aweolumidedavid your comment is incorrect - you are suggesting to create a node.js endpoint; however, we state that we use PostgREST in the starkflare-indexer repo README

This issue remains open. @KeneePatel if you are up for it can you add instructions on how would you solve this issue, according to our contributor guidelines

**Comment by aweolumidedavid** [comment]
@mazurroman I will like to give this another shot.
Following thex eisting structure of the codebase. I will solve this issue by doing the following:
- I will add a new SQL Migration File by creating it the database/migration folder and I will used the name as follows 003_add_get_transactions_by_contract_and_entrypoint.up.sql
- Next I will update the account-call.ts file because this file handles the data transformation for indexing and also ensure it aligns with the schema changes if necessary. No changes are needed here unless the schema or logic for storing data changes.

The sql code snippet look like this
CREATE OR REPLACE FUNCTION starkflare_api.get_transactions_by_contract_and_entrypoint(
    contract_hash TEXT,
    entrypoint_selector TEXT
) RETURNS TABLE (
    tx_hash TEXT,
    steps_consumed INTEGER,
    timestamp TIMESTAMP
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        tx_hash, 
        steps_number AS steps_consumed, 
        to_timestamp(timestamp) AS timestamp
    FROM 
        starkflare_api.account_calls
    WHERE 
        contract_address = contract_hash
        AND entrypoint_selector = entrypoint_selector
    ORDER BY 
        steps_number DESC;
END;
$$ LANGUAGE plpgsql;

Finally, I am open to corrections and willing to learn. Thank you very much.

**Comment by barabanovro** [comment]
Hi everyone! Thank you for your interest in this issue. @KeneePatel, your comment lacks the specific info we need according to our contribution guidelines. We expect details about you, your relevant experience, and detailed technical instructions on how you plan to tackle the task.

I have assigned this issue to @aweolumidedavid based on their last comment, which provided the necessary information and understanding of the problem and solution.

**Comment by aweolumidedavid** [comment]
Thank you very much, working on it right away @mazurroman @barabanovro

**Comment by saimeunt** [comment]
Hey @aweolumidedavid are you still working on this?
@barabanovro Following up on my work on #23 and #28 I'd like to tackle this one over the weekend if possible.

**Comment by barabanovro** [comment]
Hi @aweolumidedavid, I wanted to check in on the progress of this task. Could you please provide an update?

**Comment by aweolumidedavid** [comment]
@barabanovro @mazurroman I hope this message finds you well. I regret to inform you that I am currently unable to complete the issue assigned to me due to unforeseen circumstances that have taken me away for a while. Given the importance of timely progress on this matter, I kindly request that the issue be reassigned to another team member @saimeunt who can continue the work without delay.
I value the work we are doing and remain committed to contributing effectively. Once I am back, I will be more than happy to pick up new issues and continue supporting our projects.
Thank you for your understanding and support during this time.

**Comment by JoelVR17** [comment]
I'd like to tackle this issue for several reasons. Firstly, I have experience in developing RESTful APIs and working with some databases. Moreover, I've carefully reviewed the requirements of the problem and feel confident in implementing the API endpoint as specified. I'm committed to adhering to project guidelines and have the availability to efficiently complete this task. In summary, I believe I can effectively contribute to resolving this issue, and I'm excited about the opportunity to work on it.
