### ISSUE TITLE
Data tile FE: Entrypoints and Transactions

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#11]
Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

Related backend tasks:
* https://github.com/walnuthq/starkflare/issues/9
* https://github.com/walnuthq/starkflare/issues/10

Implement the "Entrypoints and Transactions" tile (file named `entrypoints.tsx`) based on the following description and mock.
* It should contain an input field, where the user can specify a contract ID. The default contract ID will be pre-set to [Carmine](https://starkscan.co/contract/0x047472e6755afc57ada9550b6a3ac93129cc4b5f98f51c73e0644d129fd208d9#overview)
* It should contain a list of Entrypoints of a given contract, sorted by the amount of steps used. Use vertical scroll if the list is too large
* Above entrypoints, there will be a visualisation of each entrypoint usage. See the "Visual inspiration for the Entrypoints section" screenshot below
* On the right side, there will be a "Transactions" section with a list of transactions for a selected Entrypoint. It will be possible to select a different entrypoint using a little select box in the description below "Transactions" header (see mock below). Each transaction will contain a hash and a number of steps consumed. Bonus points for also showing the timestamp of the transaction.

Visual inspiration for the Entrypoints section:  ![CleanShot 2024-05-20 at 15 38 44@2x](https://github.com/walnuthq/starkflare/assets/2983746/3fe40f93-1180-4e83-8821-02cab646f07b)

Mock of the whole tile:
<img width="956" alt="image" src="https://github.com/walnuthq/starkflare/assets/2983746/30746345-32b6-47c5-9088-29ab63338b6c">

Note: if the backend tasks are not ready, it's OK to mock the data in a hardcoded JSON.

**Specification missing: ‼️**
Update based on our ability to get the data from the API; cc @barabanovro

**Comment by bhavyagosai** [comment]
Hey, I have been at frontend development since a while now. Saw the project is using nextjs + tailwindcss + shadcn/radix where I have significant experience. I can pick this issue up if its okay. You can assign it to me as odhack starts!

**Comment by melnikga** [comment]
Can I take this?

**Comment by khayss** [comment]
Can I take up this issue?

**Comment by Ugo-X** [comment]
Hello good evening @mazurroman my name is Ugonna from Nigeria and I am a full-stack developer. I have worked on quite a number of projects before now, including previous OD hacks. You can check my profile to see my contributions. I am very swift and effective in handling tasks. From the issue above I plan on tackling it by following the brief mockup design and also incorporating elements from the design inspo while making sure to adhere to the specifications for any part of the feature.

**Comment by VictoriaAde** [comment]
Hi, I have a good idea of how this would work.
I am a developer with a good years of experience.
I would like to work on this.

**Comment by mazurroman** [comment]
Thank you to everyone interested!

@bhavyagosai I am assigning it to you because your comment was first and very thorough. Your past experience also shows that you should have the relevant skills to work on this task. Good luck!
