### ISSUE TITLE
Add nudge to contribute to the Starkflare codebase

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#14]
At the bottom of the app (above footer) add a title with a button that will encourage people to contribute to this project.

Title text: Have ideas to make cairovm.codes better?
Button text: Contribute on GitHub
Link url: https://github.com/walnuthq/starkflare

Visual inspiration: https://cairovm.codes/ (scroll down to the relevant section)

Contributor guidelines: https://github.com/walnuthq/starkflare/issues/12

**Comment by jaipaljadeja** [comment]
i can take this 👀

**Comment by BlackStarkGoku** [comment]
Hello, I would love to contribute for this one, this is not my first time in a Walnut repo, but will be on this project! I think this will drive me to explore the code. I am a Frontend Software Engineer

**Comment by mazurroman** [comment]
Thanks for the speedy comments! Please note we will start assigning issues tomorrow, when the OD Hack starts

**Comment by NueloSE** [comment]
Hi @mazurroman. My name is Nuelo, am a developer proficient in React, Next.js, Typescript, js, css.

Plans to tackle this task:

- Create a new component containing the button  `ContributeBanner.tsx` and place it in the components directory.
- Create a CSS module for the new component to style it.
- Inside `../src/app/layout.tsx` file, i will include `contributeBanner` component just above the footer.
- Finally make a PR

**Comment by Mario-Araya** [comment]
@mazurroman Hello everyone! 👋 I'm Mario Araya, and I'm excited to make my first contribution to the Starkflare codebase.

To accomplish this task, I plan to edit the main page of the Starkflare repository, specifically the README.md file. I'll add a friendly nudge encouraging potential contributors to join our community and contribute to the project. This could include information on how to get started, where to find help, and how contributions are appreciated.

Looking forward to collaborating with all of you!

Best regards,
Mario Araya

**Comment by danielcdz** [comment]
Hello! I would like to help with this one !
I think this issue can take me about 2 to 5 days to completed exactly the time limit of the OD Hack!
I have over 3 years of experience as a software engineer and I want to learn about web3 and blockchain, this is my 2nd OD Hack 🫡

**Comment by DanielEmmanuel1** [comment]
Hello @mazurroman I'll like to take this project, although this will be my first OD hack project, I'm am confident in my abilities to complete this project to the utmost perfection and within the allocated time.

**Comment by vibenedict** [comment]
i will like to jump on this issue

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this

**Comment by devcollinss** [comment]
Hello @mazurroman, My name is Collins. I am a Fullstack Developer. I would love to contribute to resolving this issue.
