### ISSUE TITLE
Data tile: Total users

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#2]
**⚠️ ATTENTION:** This is a DRAFT task for the upcoming OD Hack. We will start assigning issues after Thursday, May 23rd. Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

Add number of users incl diff from last period (new vs lost)
Add question mark with info about the tile (TBD: copy)

**Comment by raizo07** [comment]
@mazurroman I'll like to work on this.

**Comment by mazurroman** [comment]
@raizo07 thanks for your interest in helping us!

Please check our [contributor guidelines](https://github.com/walnuthq/starkflare/issues/12) before commenting on issues.

I am assigning this one to a member of our internal team, because we want to have this tile done by tomorrow, to have an example ready for the start of ODHack 4. Please check other issues and add a comment after reading the [contrib guidelines](https://github.com/walnuthq/starkflare/issues/12).

**Comment by Mario-Araya** [comment]
@mazurroman Hello Starkflare team! 👋 I'm Mario Araya, and I'm thrilled to contribute to enhancing the data visualization capabilities of Starkflare.

To address this issue, I plan to focus on the data tile component responsible for displaying total users. I'll be working on the relevant React component files, including JavaScript and possibly CSS, to implement this feature. This may involve fetching data from the backend API, processing it, and rendering it in a visually appealing and informative manner.

I'll ensure that the total users data tile is intuitive, informative, and seamlessly integrated into the existing user interface of Starkflare.

Excited to make a meaningful contribution!

Best regards,
Mario Araya
