### ISSUE TITLE
The app returns an error

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#35]
![CleanShot 2024-06-05 at 13 16 17@2x](https://github.com/walnuthq/starkflare/assets/2983746/4f97bfaf-ce17-4227-bc71-7ecbcc6e60e4)

**Comment by jaipaljadeja** [comment]
i can take a look.

**Comment by melnikga** [comment]
I can take this

**Comment by od-hunter** [comment]
Can I be assigned this issue please? Will deliver ASAP!

**Comment by Shoetan** [comment]
I think some vercel environment variables are missing or something to do with next-auth

**Comment by jaipaljadeja** [comment]
To me it seems like its not an issue with frontend, but with backend.
> http://starkf-servi-1yasdoedwfh1-321738969.us-east-1.elb.amazonaws.com/rpc/get_common_data

This takes forever to load and then throws 504 Gateway Timeout Error. Which is why its taking a lot of time for website to load, as this endpoint is being fetched on server side.

**Comment by mazurroman** [comment]
After debating this issue internally, we will close it for now. The problem is that the load is taking a lot of time. We will need to come up with a better system to optimise the speed - will create new tasks for that at some point.

**Comment by od-hunter** [comment]
Ok sir
