### ISSUE TITLE
Data tile: transactions count & steps used

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#4]
There is a placeholder tile for the "Transactions count and steps used" data tile. The component is called TxStepsStats (`tx-steps.tsx`). It's using dummy data and so the goal is to connect the tile with the backend and "make it work".

### Backend:
Update the get_common_data function in the https://github.com/walnuthq/starkflare-indexer backend repo to include two new fields:
1. An array containing the number of transactions for each of the last 7 days.
2. An array containing the number of steps for each of the last 7 days."

Implement a new function to retrieve this data and call it from within the get_common_data function.

Note: These new fields should be added to the existing response format of get_common_data without modifying the other fields.

### Frontend
Update the frontend to meet the attached mock (labels for x and y axes, two data lines, total weekly numbers at the top of the tile for both tx count and steps used)

Mock:
<img width="407" alt="image" src="https://github.com/walnuthq/starkflare/assets/2983746/2afa2a81-69e6-4a9d-bf7d-2b3d0d3bb2a6">

Tips:
* Use the "Total users" data tile as an example. Initially it's the only tile that is already working
* This is primarily a task for the backend. If frontend help is needed, please let us know, and we will create a separate, frontend-only task that will simply consume the APIs created here and assign it to someone more experienced with frontend development.

**Comment by mazurroman** [comment]
@fishonamos thanks for your comment. Since you are new to Walnut, can you add more info according to our [contributor guidelines](https://github.com/walnuthq/starkflare/issues/12). Thank you!

**Comment by saimeunt** [comment]
Hi @mazurroman, I've previously contributed to [cairovm.codes](https://github.com/walnuthq/cairovm.codes) and I'd like to tackle this issue.

I will augment get_common_data in https://github.com/walnuthq/starkflare-indexer/blob/main/database/migrations/001_init.up.sql with the 2 new array fields needed to get the tx count and steps used for the last 7 days, this will be done in a separate PL/SQL function just like get_user_stats.

This will probably involve grouping account_calls by appropriate timestamp (eg. timestamp >= yesterday 00:00 AND timestamp < 23h59, repeat for the remaning last 6 days) and counting txs hash as well as computing the sum of steps_number.

Then in the frontend I will simply replicate what has been done for Total users and plug in the appropriate data fetched from starkflare-indexer.

**Comment by vibenedict** [comment]
i will like to jump on this issue

**Comment by fishonamos** [comment]
Comment has been updated @mazurroman .

**Comment by mazurroman** [comment]
Thank you to everyone who was interested in this issue!

According to contributor guidelines, I am assigning this task to @saimeunt who is a returning contributor and he was the first here with a detailed specification.

@fishonamos thank you for submitting the thorough technical details. While this task was assigned to @saimeunt , there are others still open and I am hoping some of them will be yours
