### ISSUE TITLE
Data tile FE: Transactions burning most steps

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#8]
⚠️ ATTENTION: This is a DRAFT task for the upcoming OD Hack. We will start assigning issues after Thursday, May 23rd. Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

Backed task for creating the API: https://github.com/walnuthq/starkflare/issues/7

The data format returned from the API:
```
tx hash, timestamp, amount of steps consumed, block number
```

The goal of this task is to update the `txs-steps-burned` component with a list of transactions that used the highest amount of steps. Each line in the list should present the transaction hash, amount of steps burned, timestamp.

Tips:
* If the backend task is not yet ready, it's OK to hardcode some dummy data on the frontend to make it ready for a demo.

**Comment by addegbenga** [comment]
I will love to work on this.

**Comment by martinvibes** [comment]
please let me work on this

**Comment by khayss** [comment]
Can I take up this issue?

**Comment by mazurroman** [comment]
Hey all! Thanks for your comments, we will assign the issue tomorrow.

New contributors: please note we have specific [contributor guidelines](https://github.com/walnuthq/starkflare/issues/6). Check them out and update the comments accordingly.

**Comment by VictoriaAde** [comment]
Hi, I have a good idea of how this would work.
I am a developer with a good years of experience.
I would like to work on this.

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this

**Comment by devcollinss** [comment]
Hello @mazurroman I'd like to be assigned this issue. I will:

Create a React component to fetch data from the backend API endpoint returning tx hash, timestamp, steps consumed, and block number.
Implement sorting/filtering logic to display transactions with highest steps consumed.
Use React hooks to manage component state and fetch data.
Style the component to match design specs.

**Comment by mazurroman** [comment]
Assigning this issue to @jaipaljadeja who is a returning contributor to Walnut

Thanks everyone else for your interest! @addegbenga your comment did provide some specific; however we would expect more technical details to get enough confidence you are up for the task. Your profile doesn't contain much contributions, it's mostly private repos or one still-open PR on cairobook with tons of open comments from Eni.

**Comment by addegbenga** [comment]
> Assigning this issue to @jaipaljadeja who is a returning contributor to Walnut
> 
> Thanks everyone else for your interest! @addegbenga your comment did provide some specific; however we would expect more technical details to get enough confidence you are up for the task. Your profile doesn't contain much contributions, it's mostly private repos or one still-open PR on cairobook with tons of open comments from Eni.

Thanks for your feedback! 😊 I'll address Eni's comments as soon as possible.

I've contributed to [Artpeace](https://github.com/addegbenga?org=keep-starknet-strange&year_list=1) and [StarkNet](https://github.com/addegbenga?from=2024-05-01&to=2024-05-23&org=starknet-id&year_list=1) before, so I feel confident in my abilities. Even if my profile doesn't seem very convincing, I'm hopeful that I'll get the chance to work on more issues in the future.

**Comment by Jemiiah** [comment]
@mazurroman  I would love to work on his work if the current assigned isn’t no longer interested and i will take 2 working day at most to complete the issue

**Comment by 0xdevcollins** [comment]
Hello @mazurroman can you please assign the task to me. I will complete is as soon as possible

**Comment by ktarun1419** [comment]
Hi @mazurroman I want to work on this

**Comment by Joy-Adah** [comment]
Hi @mazurroman is this still available? If it is, I'd like to take it up

**Comment by mazurroman** [comment]
This project is currently on hold
