### ISSUE TITLE
Data tile BE: Entrypoints burning most steps

### ISSUE THREAD

**Issue by mazurroman** [walnuthq/starkflare#9]
Feel free to join our telegram to get latest updates: https://t.me/+DYI4FMia43I1NDI8

### Implement API endpoint for contract entrypoint steps consumption

1. Create an API endpoint in the `starkflare-indexer` backend https://github.com/walnuthq/starkflare-indexer that accepts a contract hash as a parameter and returns a list of entrypoints for the given contract, sorted by the total number of steps consumed over the last 7 days.

2. For each entrypoint, the endpoint should return:
   - Entrypoint selector
   - Total number of steps consumed
   - Percentage of steps consumption compared to other entrypoints in the contract

3. Follow the guidelines in the `starkflare-indexer` repository when implementing this new endpoint.

### Create Next.js server API endpoint for enhanced contract entrypoint data

1. Implement a new API endpoint in this Next.js repository that fetches data from the `starkflare-indexer` endpoint created in the previous step.

2. Enhance the data returned by the `starkflare-indexer` endpoint by adding entrypoint names to the response. To obtain the entrypoint names:
   - Fetch the contract ABI from the node provider
   - Use the ABI to map entrypoint selectors to their corresponding names

3. The final response from this Next.js API endpoint should include:
   - Entrypoint selector
   - Entrypoint name
   - Total number of steps consumed
   - Percentage of gas consumption compared to other entrypoints in the contract

4. Ensure proper error handling and validation of the data received from the `starkflare-indexer` endpoint.

**Comment by EmmanuelAR** [comment]
Hey @mazurroman can i work on this ?

**Comment by khayss** [comment]
Can I take up this issue?

**Comment by EmmanuelAR** [comment]
Hey @mazurroman @barabanovro 
To complete this task I will:
- I fist create the endpoint that return the contract data that I received from parameters in order, 
- To build it, I will check the old endpoints created in the project, to give an idea of how is now created, error validations comments etc 
- Once finishing the first endpoint I will create the second one in nextJs. I understand that for that I have to call the first one that I create.
- As the first one I will check the old implementations just to take an idea of how to create and code it.
- I will follow all the code rules, styles and formats.
- I will attend to ask questions and ask to the dev team.
- This is my first time working on this project so I am very excited to do it.

Telegram: @EmmanuelDevCr

Let me know,team!

**Comment by Ugo-X** [comment]
Hello good evening @mazurroman   my name is Ugonna from Nigeria and I am a full-stack developer. I have worked on quite some projects before now, including previous OD hacks. You can check my profile to see my contributions. I am very swift and effective in handling tasks.
Please can I be assigned this issue?

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this 🙂

**Comment by mazurroman** [comment]
Hi all! Thank you for your interest in this issue and for your comments. Unfortunately, none of the comments convinced us to assign the issue. @EmmanuelAR yours is the most verbose, however its still lacking any specific information and your GitHub profile is not very active on Open Source.

If someone is up for the issue, please comment according to our contributor guidelines

**Comment by Ugo-X** [comment]
Hello good evening @mazurroman my name is Ugonna and I am a full-stack developer. I have worked on quite some projects before now, including previous OD hacks. You can check my profile to see my contributions.


Here's a breakdown of how I can implement the API endpoints to retrieve contract entrypoint data consumption information:

Step-by-Step Approach:

1. New API Endpoint (Go):
   - I'll create a new endpoint in the Starkflare-Indexer backend (written in Go) to handle contract entrypoint data requests.
   - This endpoint will accept the contract hash as a parameter in the URL.
2. Data Retrieval and Processing:
   - Inside the endpoint handler, I'll use the provided contract hash to query the database for relevant entrypoint data.
   - I'll filter the data to only include entries from the past 7 days.
   - I'll calculate the total steps consumed for each entrypoint.
   - Additionally, I'll calculate the percentage of steps each entrypoint consumed compared to the total for the entire contract.
3. Response Formatting:
   - I'll format the response as a JSON object containing an array of objects. Each object will represent an entrypoint and include:
      - `selector`: The unique string identifying the entrypoint.
      - `totalSteps`: The total number of steps consumed.
      - `percentage`: The percentage of steps consumed compared to others (rounded to two decimal places).

Next.js API Route (JavaScript):

1. Fetching Data:
   - I'll create a new API route in the Next.js application to handle requests for entrypoint data.
   - This route will also accept the contract hash as a URL parameter.
2. Calling the Starkflare-Indexer Backend:
   - I'll utilize the `fetch` API or a dedicated library to call the `/contracts/:hash/entrypoints` endpoint in the Starkflare-Indexer backend.
3. Error Handling:
   - It's important to handle potential errors during the API call, such as network issues or invalid responses.
4. ABI Fetching:
   - I'll leverage a library like `@ethersproject/contracts` to connect to a Starknet node and fetch the contract's ABI (Application Binary Interface) using the contract hash.
5. Entrypoint Mapping:
   - After retrieving the ABI, I'll iterate through the entrypoint selectors obtained from the Starkflare-Indexer response.
   - For each selector, I'll search the ABI for the corresponding function signature and extract the human-readable function name (entrypoint name).

Combining Information and Final Response:

- I'll combine the data from both responses (Starkflare-Indexer and ABI) to create the final response.
- The final response will be a JSON array containing objects for each entrypoint, with the following properties:
   - `selector`: The unique entrypoint selector string.
   - `entrypointName`: The human-readable name extracted from the ABI.
   - `totalSteps`: The total number of steps consumed (from Starkflare-Indexer).
   - `percentage`: The percentage of steps consumed compared to others (from Starkflare-Indexer).

Additional Considerations:

- I'll implement data validation for the received contract hash in both API endpoints.
- I'll ensure proper documentation of the new API endpoints within each repository.
- Unit testing the new endpoints is recommended for code reliability.

 I'll refer to the provided guidelines in the `starkflare-indexer` repository for best practices.

By following these steps, I can effectively implement the API endpoints and retrieve the desired contract entrypoint data consumption information.

Additionally, I have a consistently active GitHub profile showcasing my contributions to Open Source projects.

I believe this comprehensive approach demonstrates my understanding of the task and my ability to contribute effectively.   I'm confident I can successfully implement this feature!

Please can I be assigned this issue?

**Comment by Ugo-X** [comment]
> Hi all! Thank you for your interest in this issue and for your comments. Unfortunately, none of the comments convinced us to assign the issue. @EmmanuelAR yours is the most verbose, however its still lacking any specific information and your GitHub profile is not very active on Open Source.
> 
> If someone is up for the issue, please comment according to our contributor guidelines

Hello good Morning @mazurroman mazurroman my name is Ugonna and I am a full-stack developer. I have worked on quite some projects before now, including previous OD hacks. You can check my profile to see my contributions.


Here's a breakdown of how I can implement the API endpoints to retrieve contract entrypoint data consumption information:

Step-by-Step Approach:

1. New API Endpoint (Go):
   - I'll create a new endpoint in the Starkflare-Indexer backend (written in Go) to handle contract entrypoint data requests.
   - This endpoint will accept the contract hash as a parameter in the URL.
2. Data Retrieval and Processing:
   - Inside the endpoint handler, I'll use the provided contract hash to query the database for relevant entrypoint data.
   - I'll filter the data to only include entries from the past 7 days.
   - I'll calculate the total steps consumed for each entrypoint.
   - Additionally, I'll calculate the percentage of steps each entrypoint consumed compared to the total for the entire contract.
3. Response Formatting:
   - I'll format the response as a JSON object containing an array of objects. Each object will represent an entrypoint and include:
      - `selector`: The unique string identifying the entrypoint.
      - `totalSteps`: The total number of steps consumed.
      - `percentage`: The percentage of steps consumed compared to others (rounded to two decimal places).

Next.js API Route (JavaScript):

1. Fetching Data:
   - I'll create a new API route in the Next.js application to handle requests for entrypoint data.
   - This route will also accept the contract hash as a URL parameter.
2. Calling the Starkflare-Indexer Backend:
   - I'll utilize the `fetch` API or a dedicated library to call the `/contracts/:hash/entrypoints` endpoint in the Starkflare-Indexer backend.
3. Error Handling:
   - It's important to handle potential errors during the API call, such as network issues or invalid responses.
4. ABI Fetching:
   - I'll leverage a library like `@ethersproject/contracts` to connect to a Starknet node and fetch the contract's ABI (Application Binary Interface) using the contract hash.
5. Entrypoint Mapping:
   - After retrieving the ABI, I'll iterate through the entrypoint selectors obtained from the Starkflare-Indexer response.
   - For each selector, I'll search the ABI for the corresponding function signature and extract the human-readable function name (entrypoint name).

Combining Information and Final Response:

- I'll combine the data from both responses (Starkflare-Indexer and ABI) to create the final response.
- The final response will be a JSON array containing objects for each entrypoint, with the following properties:
   - `selector`: The unique entrypoint selector string.
   - `entrypointName`: The human-readable name extracted from the ABI.
   - `totalSteps`: The total number of steps consumed (from Starkflare-Indexer).
   - `percentage`: The percentage of steps consumed compared to others (from Starkflare-Indexer).

Additional Considerations:

- I'll implement data validation for the received contract hash in both API endpoints.
- I'll ensure proper documentation of the new API endpoints within each repository.
- Unit testing the new endpoints is recommended for code reliability.

 I'll refer to the provided guidelines in the `starkflare-indexer` repository for best practices.

By following these steps, I can effectively implement the API endpoints and retrieve the desired contract entrypoint data consumption information.

Additionally, I have a consistently active GitHub profile showcasing my contributions to Open Source projects.

I believe this comprehensive approach demonstrates my understanding of the task and my ability to contribute effectively.   I'm confident I can successfully implement this feature!

Please can I be assigned this issue?

**Comment by KeneePatel** [comment]
Here's the approach I will follow:
- Clone starkflare-indexer and set up the environment according to the guide. 
- Create the endpoint that accepts the given inputs and responds to it as described in the issue. 
- Test the endpoint thoroughly manually ensuring it passes every scenario and edge cases.
- Make the PR and reference it here.
- Let the contributor review it. If it looks good, awesome. Or else, make the required change.

**Comment by barabanovro** [comment]
Hello! Thanks for your interest in this issue.

@Ugo-X, while your comment is detailed, there's a misunderstanding. Starknet isn't EVM compatible, so @ethersproject/contracts won't work here.

@KeneePatel, please provide more specific insights related to the issue.

If anyone is interested in tackling this, comment with a clear approach and relevant experience, following our contributor guidelines.

Thanks for your understanding!

**Comment by Ugo-X** [comment]
> Hello! Thanks for your interest in this issue.
> 
> @Ugo-X, while your comment is detailed, there's a misunderstanding. Starknet isn't EVM compatible, so @ethersproject/contracts won't work here.
> 
> @KeneePatel, please provide more specific insights related to the issue.
> 
> If anyone is interested in tackling this, comment with a clear approach and relevant experience, following our contributor guidelines.
> 
> Thanks for your understanding!

hello @mazurroman 
being that starknet is not EVM compatible, i would do away with the ether contracts fetching and instead construct the final response using the response from the starkflare-indexer and the entrypoint mapping data.

**Comment by mazurroman** [comment]
@Ugo-X, thank you for your message. It should have already been clear from your previous comment that Starknet is not EVM compatible.

For this ODHack, we have people with more experience, so at the current moment, we won't assign issues to you. We encourage you to continue learning and building up your experience so that you can be assigned complex issues like this in the near future!

**Comment by Ugo-X** [comment]
> @Ugo-X, thank you for your message. It should have already been clear from your previous comment that Starknet is not EVM compatible.
> 
> For this ODHack, we have people with more experience, so at the current moment, we won't assign issues to you. We encourage you to continue learning and building up your experience so that you can be assigned complex issues like this in the near future!

alright, Chief, I thought it was something I could handle but apparently, it's not. I will keep working and get better, thanks for taking the time to reply to me comprehensively

**Comment by KeneePatel** [comment]
JM @barabanovro,

Thank you for the reply. I will try to be very specific this time.

Let me start by giving a bit of context about me. I am an Applied Computer Science Grad student at Dalhousie University, trying to juggle studies and do my best to contribute in opensource at the same time. I have some experience in mysql, mongodb for my personal, group and college projects, but not with postgreSQL. However, I am confident in my abilities to search for solutions and find a way to tackle all the hurdles.

Coming to the approach on how I will tackle the issue.
- Setup the environment for starkflare and starkflare-indexer. I have already followed the steps and have the environment setup on my local machine with the help of docker.
- First main step would be to make the backend api working:
    - For that I will need to make a function which will accept the contract hash.
    - After accepting the contract hash, I will need to implement the code to get the entrypoints for the contract. (I am guessing it will involve using the ABI of that contract)
    - After getting all the entrypoints, I will need to create a logic to get the total number of steps consumed over the last 7 days by that entrypoint.
    - Sort it with the number of steps consumed.
    - Make percentage from number of steps. (I had a doubt on this one. Wouldn't it be better to do the conversion on the frontend rather than the backend and just let the backend return number of steps consumed.)
    - return that
- After the main backend step is done. I will follow it along by consuming this api endpoint with next.js making it usable in the frontend with proper structuring as mention in the issue description.

I am already in the TG server and will be communicating my progress, or any decision that I may be met with. Let me know if I missed anything else :D

**Comment by saimeunt** [comment]
Hi @barabanovro, following up my work on #4 I'd like to continue working on this project now that I have a better understanding of its architecture.

Here is how I will handle this issue:

### starkflare-indexer API endpoint:

I will add a new PL/SQL function following the README guidelines to automatically generate a corresponding REST endpoint thanks to PostgREST.
This function will take the contract address (you specified contract hash but you meant address correct me if I'm wrong?) parameter and use an SQL query to fetch every AccountCall having this particular contract address as target.
The AccountCalls relative to the queried contract address will be grouped by entrypoint_selector to compute the number of steps SUM and the percentage of steps used in comparison with the other entrypoints.

### Next.js API endpoint:

I will define a new GET route in the api folder to consume the previously defined indexer endpoint and use Starknet.js to enhance the data with entrypoint names using their selector.
In particular I will use the getClassAt function to fetch the ABI from the contract address and match the selector with its corresponding human readable name.

**Comment by barabanovro** [comment]
Thanks for your comments! @KeneePatel, your comment was detailed, but I'm assigning this issue to @saimeunt as their comment provides the specific entrypoint names mapping details needed to resolve this issue.
